# Use root/example as user/password credentials
version: '3'
services:

  banco:
    command: mysqld --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    build: 
      context: .
      dockerfile: mysql.dockerfile
    container_name: banco-desafio-proposta
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123321475
      MYSQL_DATABASE: PropostaNova
    networks:
      - desafio-proposta

  bootcamp:
    build: 
      dockerfile: Dockerfile
      context: .
    image : proposta-teste:1.0
    restart: on-failure
    ports:
      - "8081:8081"
    links:
      - banco
    depends_on:
      - banco
    networks:
      - desafio-proposta
networks: 
    desafio-proposta :
      driver: bridge
  
  