version: '3'
services:

  desafio-proposta-banco:
    image: mysql:latest
    container_name: proposta-banco
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123321475
      - MYSQL_DATABASE=desafio-proposta

  proposta:
    build:
      dockerfile: Dockerfile
      context: .
    image: proposta
    container_name: proposta
    ports:
      - "8080:8080"

